"""Domain models used across the application."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List


@dataclass
class DocumentPage:
    """Represents parsed content from a PDF page."""

    page_number: int
    text: str
    elements: List[Dict[str, Any]] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class ParsedDocument:
    """Represents the parsed document and metadata."""

    source_name: str
    pages: List[DocumentPage]
    metadata: Dict[str, Any] = field(default_factory=dict)
    preview_images: List[Any] = field(default_factory=list)


@dataclass
class WorkflowStep:
    """Represents one procedural workflow step."""

    step_id: str
    title: str
    description: str
    role: str = "Operator"
    inputs: List[str] = field(default_factory=list)
    outputs: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class WorkflowResult:
    """Output generated by the AI workflow service."""

    workflow_steps: List[WorkflowStep]
    sop_markdown: str
    structured_json: Dict[str, Any]
    metrics: Dict[str, Any]
    embedding_payload: List[Dict[str, Any]] = field(default_factory=list)
